version: "3.9"

services:

  backend:
    build: .
    container_name: jp-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5001/api
    container_name: jp-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - backend-network

  mongo:
    image: mongo:7
    container_name: jp-mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network
    # ⚠️ NOTICE: No ports exposed anymore

volumes:
  mongo_data:


networks:
  backend-network:
    driver: bridge
