apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: jp-app
type: Opaque
stringData:
  ADMIN_SEED_EMAIL: "admin@jpapp.com"
  ADMIN_SEED_PASSWORD: "jpeljaiko1854#"
  BCRYPT_SALT: "10"
  MONGODB_URI: "mongodb://mongo-service:27017/jpgroup"
  OTP_SECRET: "pk_test_aW5jbHVkZWQtbG91c2UtOC5jbGVyay5hY2NvdW50cy5kZXYk"
  RATE_LIMIT_MAX_REQUESTS: "100"
  RATE_LIMIT_WINDOW_MS: "900000"
  UPLOAD_PATH: "./uploads"
  JWT_EXPIRE: "7d"
  JWT_SECRET: "your-super-secret-jwt-key-here"
  GMAIL_APP_PASSWORD: "pjzt ihqj rrey hkom"
  SMTP_HOST: "smtp.rediffmailpro.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "media@jpel.in"
  SMTP_PASS: "M6%e@d8^&"
  SMTP_FROM: "media@jpel.in"
  MAX_FILE_SIZE: "10485760"
